/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kutuphane;

import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author baris
 */
public class BookList extends javax.swing.JFrame {

    /**
     * Creates new form BookList
     */
    DBConnect baglanti= new DBConnect();
    PreparedStatement pat= null;
    ResultSet rs= null;
    Statement st=null;
 
     // public  java.sql.Connection connection ;   
    
    public BookList() {
        initComponents();
         this.setLocationRelativeTo(null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchdata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 730, 230));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Listele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 106, 145, 40));

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                Library System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel6)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setText("Geri");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kitap Ara:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 106, 80, 32));

        searchdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdataActionPerformed(evt);
            }
        });
        searchdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchdataKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchdataKeyReleased(evt);
            }
        });
        getContentPane().add(searchdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 109, 165, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Barış\\Downloads\\kutuphane11.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 730, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try { //OLUŞTURDUĞUMUZ BAĞLANTI SINIFINI ÇAĞIRMA
            DBConnect baglantii = new DBConnect();
            //BAGLANTI SINIFINDAN BAGLANTI AÇMA FONKSİYONUNUN ÇAĞIRILMASI
            baglantii.connectToDB();     
            // BAĞLANTI VE CONN KOMUTLARINI BİRLEŞTİREN VE DENETLEYEN KODLAR
            Statement st = (Statement) baglantii.connection.createStatement();
            //ÇALIŞTIRILACAK SORGU
            rs = st.executeQuery("Select * from kitaplar");
            //VERİTABANINDA BULUNAN SÜTÜNLARI SAYDIRMA
            int colcount = rs.getMetaData().getColumnCount();
            //MODEL OLUŞTURMA
            DefaultTableModel tm = new DefaultTableModel();
            for(int i = 1;i<=colcount;i++)
                 //TABLOYA VERİTABANINDAKİ SUTUNLARLA AYNI OLACAK ŞEKİLDE SUTUN EKLEME
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next())
                {
                    //BİR DİZİDE TABLODAKİ SUTUNLARIN TUTULMASI
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    //TABLOYA EKLENMESİ
                    tm.addRow(row);
            }
            jTable1.setModel(tm);
            //SERVER BAĞLANTISININ KAPATILMASI
            baglantii.connection.close();
	}//BAGLANTI HATASINDA GÖSTERİLECEK MESAJ 
        catch (Exception e){System.out.println(e.toString());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdataActionPerformed
         
    }//GEN-LAST:event_searchdataActionPerformed

    private void searchdataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchdataKeyReleased
        
    }//GEN-LAST:event_searchdataKeyReleased

    private void searchdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchdataKeyPressed
   try{   
       DBConnect baglanti= new DBConnect();
          String url = "jdbc:sqlserver://localhost:1433;user=sa;password=q1w2e3r4t5;" +
            "databaseName=LibraryDB;";
       baglanti.connection = DriverManager.getConnection(url);
        Statement st = baglanti.connection.createStatement();
        String query = "SELECT* FROM kitaplar WHERE kitapadi LIKE '%" + searchdata.getText() + "%'";
      rs = st.executeQuery(query);
      jTable1.setModel(DbUtils.resultSetToTableModel(rs)); 
baglanti.connection.close(); 
}
     catch (Exception e) { 
        JOptionPane.showMessageDialog(null,"Got an exception!");
        System.err.println(e.getMessage()); 
    }   
    }//GEN-LAST:event_searchdataKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       MainMenu _menu= new MainMenu();
      _menu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchdata;
    // End of variables declaration//GEN-END:variables
}
