/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kutuphane;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author baris
 */
public class EditBook extends javax.swing.JFrame {

    /**
     * Creates new form EditBook
     */
       DBConnect baglanti= new DBConnect();
       
    PreparedStatement pat= null;
    ResultSet set= null;
    Statement stmt= null;
    public EditBook() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kitapadi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sayfasayi = new javax.swing.JTextField();
        yazaradi = new javax.swing.JTextField();
        barkod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        stoksayisi = new javax.swing.JTextField();
        yayinevi = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ciltno = new javax.swing.JTextField();
        kitaptürü = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Barkod:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barkod:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sayfa Sayısı:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yazar Adı:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 79, 33));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stok Sayısı:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Yayın Evi:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 73, 33));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kitap Türü:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 73, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cilt No:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 73, 33));
        getContentPane().add(kitapadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 30));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 150, 30));
        getContentPane().add(sayfasayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 30));
        getContentPane().add(yazaradi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, 30));
        getContentPane().add(barkod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 140, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kitap Adı:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 33));
        getContentPane().add(stoksayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, 30));
        getContentPane().add(yayinevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 140, 30));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 150, 30));
        getContentPane().add(ciltno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 140, 30));
        getContentPane().add(kitaptürü, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Barış\\Desktop\\İcons\\kutuphane16.jpg")); // NOI18N
        jLabel2.setText("ssssss");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
        DBConnect baglantii=new DBConnect();
        baglantii.connectToDB();   
        stmt=(Statement) baglantii.connection.createStatement();     
        if(!(barkod.getText().isEmpty()) && !(kitapadi.getText().isEmpty()))
        {   //Burda sql de ki columnlarla eşleşio iste 
            String sql= "Update kitaplar SET barkod='"+barkod.getText() + "',kitapadi='" + kitapadi.getText() +"',sayfasayisi='"+sayfasayi.getText() +"',yazaradi='"+yazaradi.getText()+ "',stoksayisi='"+stoksayisi.getText()+"',yayinevi='"+yayinevi.getText()+"',ciltno='"+ciltno.getText()+"',kitaptürü='"+kitaptürü.getText()+ "' where barkod='"+barkod.getText()+"'";
            //sorguyu cagırıo
            stmt.executeUpdate(sql);
            //eklenirse gelecek olan mesaj
            JOptionPane.showMessageDialog(null, "Kayıt Yenilendi!");
            baglantii.connection.close();
            //kayıt tamamlanınca değerler tekrar sıfırlanıo yani boş oluo
            barkod.setText("");
            kitapadi.setText("");
            sayfasayi.setText("");
             yazaradi.setText("");
            stoksayisi.setText("");
            yayinevi.setText("");
            yayinevi.setText("");
            ciltno.setText("");
            kitaptürü.setText("");
            
            
             }
        else{JOptionPane.showMessageDialog(null, "Boş Alanları Doldurunuz!");}
        } //baglantıda hata olursa gelecek mesaj
        catch (Exception e){e.printStackTrace();}
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainMenu menu= new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barkod;
    private javax.swing.JTextField ciltno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kitapadi;
    private javax.swing.JTextField kitaptürü;
    private javax.swing.JTextField sayfasayi;
    private javax.swing.JTextField stoksayisi;
    private javax.swing.JTextField yayinevi;
    private javax.swing.JTextField yazaradi;
    // End of variables declaration//GEN-END:variables
}
